name: "sors"
url: "https://www.cbr.ru/statistics/bank_sector/sors/"
paths:
  - "Кредиты, предоставленные юридическим лицам - резидентам и индивидуальным предпринимателям (в целом по Российской Федерации)":
      - "Информация о количестве заемщиков и предоставленных кредитов"
  - "Кредиты, предоставленные юридическим лицам - резидентам и индивидуальным предпринимателям (региональный разрез)":
      - "Задолженность, в том числе просроченная, по кредитам, предоставленным юридическим лицам — резидентам и индивидуальным предпринимателям, по видам экономической деятельности и отдельным направлениям использования средств (на дату)"
  - "Кредиты, предоставленные субъектам малого и среднего предпринимательства (региональный разрез)":
      - "Задолженность, в том числе просроченная, по кредитам, предоставленным субъектам малого и среднего предпринимательства"
      - "Задолженность, в том числе просроченная, по кредитам, предоставленным субъектам малого и среднего предпринимательства — индивидуальным предпринимателям"

---

name: "review"
url: "https://www.cbr.ru/statistics/bank_sector/review/"
paths:
  - "«Статистические показатели банковского сектора Российской Федерации» (Интернет–версия)"

---

name: "obs"
url: "https://www.cbr.ru/Content/Document/File/115862/obs_tabl20%D1%81.xlsx"